---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople.cpwgmysulhar.eu-west-1.rds.amazonaws.com
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople
    TYPEORM_DATABASE: udapeople
  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      command: sleep 300s 

    - name: "install python for Ansible."
      apt:
        name: python
        state: present

  roles:
    - configure-server 
