---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:  
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Basic usage
  become: yes 
  debug:
      msg: "'{{ lookup('env', 'TYPEORM_CONNECTION') }}' is the HOME environment variable."
      #msg: "'{{ lookup('env', 'HOMIE') | default('/home/abraam', True) }}' is the user."   
