---

- name: Create APP Directory
  become_user: ubuntu
  become: yes
  file:
    path: ~/app
    state: directory

- name: "Copy node app files"
  become: yes
  become_user: ubuntu
  ignore_errors: True
  async: 60
  poll: 60
  synchronize:
    src: ~/project/backend/dist/
    dest: ~/backend

- name: Start PM2
  become_user: ubuntu
  become: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start 
