---

- name: Create APP Directory
  user: ubuntu
  become: yes
  file:
  	path: ~/app
	state=directory

- name: "Copy node app files"
  become: yes
  user: ubuntu
  copy:
    src: backend/dist/
    dest: ~/backend

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start 
