---

- name: Create APP Directory
  become_user: ubuntu
  become: yes
  file:
    path: ~/app
    state: directory

- name: "Copy node app files"
  become: yes
  ignore_errors: True
  unarchive:
    src: ~/project/artifacts.tar
    dest: ~/backend

- name: "unarchive"
  become: yes
  ignore_errors: True
  copy:
    src: ~/project/artifacts.tar
    dest: ~/backend
    
- name: Start PM2
  become_user: ubuntu
  become: yes
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start 
