version: 2.1

commands:

  exit-pipeline:
    description: exit pipeline if job fails
    steps:
      - run:
          name: exit pipeline
          when: on_fail
          command: |
            exit 1

  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
        backendStack:
            type: string
            default: "udapeople-back-$WorkFlowID"

        frontendStack:
            type: string
            default: "udapeople-front-$WorkFlowID"
            
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name << parameters.backendStack >>
            aws cloudformation delete-stack --stack-name << parameters.frontendStack >>

jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: install the tar package for the workspace step 
          command: |
            yum -y install tar gzip 
              
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances \
                --query 'Reservations[*].Instances[*].PublicIpAddress' \
                --filters "Name=tag:project,Values=udapeople" \
                --output text >> .circleci/ansible/inventory.txt
            
            aws ec2 describe-instances \
                --query 'Reservations[*].Instances[*].PublicDnsName' \
                --filters "Name=tag:project,Values=udapeople" \
                --output text >> back_url
            
            ec2_url=`cat back_url`
            
            curl -H "Content-Type: text/plain" -H "token: 9787990f-712f-4549-8efb-7715e8abab1c" --request PUT --data $ec2_url https://api.memstash.io/values/back_url
            url=`curl -H "token: 9787990f-712f-4549-8efb-7715e8abab1c" --request GET https://api.memstash.io/values/back_url`
            echo $url 
            
            cat .circleci/ansible/inventory.txt
            
      - persist_to_workspace:
          root: .circleci
          paths:
            - ansible/inventory.txt
      - destroy-environment
           
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints: ["09:1c:5a:d9:6d:5e:87:c8:30:ca:2c:bf:fc:eb:b6:65"]
      - attach_workspace:
            at: .       
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
            cat .circleci/ansible/inventory.txt
            
      - run:
          name: Configure server
          command: |
            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
          


workflows:
  default:
    jobs:
      - deploy-infrastructure
      - configure-infrastructure:
            requires:
                - deploy-infrastructure