---
- name: create node exporter user
  user:
    name: node_exporter
    create_home: no

- name: Download binaries
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.0.1.linux-amd64.tar.gz
    mode: '0777'

- name: execute many commands
  become: yes 
  become_user: ubuntu
  command: "{{ item }} chdir=/tmp"
  with_items:
      - tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
      - sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
      - sudo rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64   

- name: copy service file to remote 
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: starting services
  become: yes
  become_user: ubuntu
  command: "{{ item }}"
  with_items:
    - sudo systemctl daemon-reload
    - sudo systemctl enable node-exporter
    - sudo systemctl start node-exporter
    - sudo systemctl status node-exporter